# Generated by Django 5.2 on 2025-10-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0009_alter_child_options_alter_parent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creating_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('attestation', models.PositiveIntegerField(verbose_name='Номер аттестации')),
                ('is_successed', models.BooleanField(verbose_name='Аттестован')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting', to='registration.child', verbose_name='Обучающийся')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting', to='registration.school', verbose_name='Школа')),
            ],
        ),
    ]
