# Generated by Django 5.2 on 2026-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinglist',
            name='grade',
            field=models.IntegerField(default=1, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinglist',
            name='mail_link',
            field=models.URLField(blank=True, verbose_name='Диалог с родителем'),
        ),
        migrations.AddField(
            model_name='accountinglist',
            name='study_year',
            field=models.CharField(default='1', max_length=9, verbose_name='Учебный год'),
            preserve_default=False,
        ),
    ]
