# Generated by Django 5.2 on 2026-06-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountinglist_grade_accountinglist_mail_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinglist',
            name='attestation',
        ),
    ]
