# Generated by Django 5.1.1 on 2024-10-27 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('registration_address', models.CharField(max_length=128, verbose_name='Адрес регистрации')),
                ('living_address', models.CharField(max_length=128, verbose_name='Адрес проживания')),
                ('phone', models.CharField(validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')], verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('VDS', 'Ведущий специалист')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('registration_address', models.CharField(max_length=128, verbose_name='Адрес регистрации')),
                ('living_address', models.CharField(max_length=128, verbose_name='Адрес проживания')),
                ('phone', models.CharField(validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('type', models.CharField(choices=[('MUN', 'Муниципалитет'), ('ON', 'Онлайн')], max_length=3, verbose_name='Тип')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс')),
                ('note', models.TextField(blank=True, verbose_name='Замечание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='registration.child', verbose_name='Обучающийся')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_applicant', to='registration.parent', verbose_name='Заявитель')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_representative', to='registration.parent', verbose_name='Второй представитель')),
                ('cur_school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_cur_school', to='registration.school', verbose_name='Школа прикрепления')),
                ('prev_school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_prev_school', to='registration.school', verbose_name='Предыдущая школа')),
            ],
        ),
    ]
