# Generated by Django 5.1.1 on 2024-10-09 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('registration_address', models.CharField(max_length=128)),
                ('living_address', models.CharField(max_length=128)),
                ('phone', models.CharField(validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('position', models.CharField(choices=[('VDS', 'Ведущий специалист')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('registration_address', models.CharField(max_length=128)),
                ('living_address', models.CharField(max_length=128)),
                ('phone', models.CharField(validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('MUN', 'Муниципалитет'), ('ON', 'Онлайн')], max_length=3)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)])),
                ('note', models.TextField(blank=True)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notifications', to='registration.child')),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notification_applicant', to='registration.parent')),
                ('representative', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notification_representative', to='registration.parent')),
                ('cur_school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notification_cur_school', to='registration.school')),
                ('prev_school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notification_prev_school', to='registration.school')),
            ],
        ),
    ]
