# Generated by Django 5.1.1 on 2024-10-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_applicant', to='registration.parent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='cur_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_cur_school', to='registration.school'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='prev_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_prev_school', to='registration.school'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_representative', to='registration.parent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='registration.child'),
        ),
    ]
