# Generated by Django 5.1.1 on 2024-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('MBOU', 'МБОУ СОШ'), ('GBOU', 'ГБОУ СОШ')], default='MBOU', max_length=32, verbose_name='Тип образовательного учреждения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('VDS', 'Ведущий специалист')], max_length=32, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
