# Generated by Django 5.1.1 on 2024-10-20 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_notification_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='living_address',
            field=models.CharField(max_length=128, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='patronymic',
            field=models.CharField(max_length=32, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='child',
            name='registration_address',
            field=models.CharField(max_length=128, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='child',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=32, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_applicant', to='registration.parent', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='cur_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_cur_school', to='registration.school', verbose_name='Школа прикрепления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='note',
            field=models.TextField(blank=True, verbose_name='Замечание'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='prev_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_prev_school', to='registration.school', verbose_name='Предыдущая школа'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_representative', to='registration.parent', verbose_name='Второй представитель'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='registration.child', verbose_name='Обучающийся'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='living_address',
            field=models.CharField(max_length=128, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='patronymic',
            field=models.CharField(max_length=32, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='registration_address',
            field=models.CharField(max_length=128, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=32, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('MUN', 'Муниципалитет'), ('ON', 'Онлайн')], max_length=3, verbose_name='Тип'),
        ),
    ]
