# Generated by Django 5.1.1 on 2024-11-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_child_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('МБОУ СОШ', 'МБОУ СОШ'), ('ГБОУ СОШ', 'ГБОУ СОШ')], max_length=32, verbose_name='Тип образовательного учреждения'),
        ),
    ]
