# Generated by Django 5.1.1 on 2024-11-28 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='registration.employee', verbose_name='Сотрудник'),
            preserve_default=False,
        ),
    ]
