# Generated by Django 5.1.1 on 2024-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_employee_position_alter_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=32, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, choices=[('МБОУ СОШ', 'МБОУ СОШ'), ('ГБОУ СОШ', 'ГБОУ СОШ')], max_length=32, verbose_name='Тип образовательного учреждения'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, choices=[('Муниципалитет', 'Муниципалитет'), ('Онлайн', 'Онлайн')], max_length=13, null=True, verbose_name='Тип'),
        ),
    ]
