# Generated by Django 5.2 on 2025-10-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_school_online_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Обучающийся', 'verbose_name_plural': 'Обучающиеся'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявители'},
        ),
    ]
