# Generated by Django 5.2 on 2026-05-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_child_options_alter_parent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scans/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='registration.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Скан',
                'verbose_name_plural': 'Сканы',
            },
        ),
    ]
