# Generated by Django 5.2 on 2026-06-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_documentscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='name',
            field=models.CharField(default='Passport', max_length=30, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentscan',
            name='file',
            field=models.FileField(upload_to='scans/', verbose_name='Файл'),
        ),
    ]
