# Generated by Django 5.2 on 2026-06-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_documentscan_name_alter_documentscan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
