# Generated by Django 5.2 on 2026-06-11 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_notification_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')], verbose_name='Телефон'),
        ),
    ]
