# Generated by Django 5.2 on 2026-06-11 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_child_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='\\+7\\d{10}')], verbose_name='Телефон'),
        ),
    ]
