# Generated by Django 5.2 on 2026-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_parent_email_alter_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='living_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='registration_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Адрес регистрации'),
        ),
    ]
